#!/bin/sh

CHOWN=$(/usr/bin/which chown)
SQUID=$(/usr/bin/which squid)
"$CHOWN" -R proxy:proxy /var/log/squid
"$CHOWN" -R proxy:proxy /var/spool/squid
"$CHOWN" -R proxy:proxy /var/log/squid3

# Generate Squid Login form env vars
htpasswd -bc /etc/squid3/users "${SQUID_USERNAME}" "${SQUID_PASSWORD}"
# -c argument deletes then creates the file.
# For multiple logins, manually delete the file then cycle through the user/pass combos

# Set Squid Port
sed -i "s/http_port.*/http_port $SQUID_PORT/g" /etc/squid/squid.conf

# Set Max Children
sed -i "s/auth_param basic children.*/auth_param basic children $SQUID_MAX_CHILDREN/g" /etc/squid/squid.conf

# Workaround: Squid sometimes has stale PID file issue when stop/restart on container happens
# we need to delete the pid file before starting it again.
rm -rf /var/run/squid.pid

# Start Squid
/usr/sbin/squid -f /etc/squid/squid.conf -NYCd 1